### PR TITLE
Updating version information to work with current silex

### PR DESCRIPTION
**Pull request by lstrojny**
- Require silex 1.\* instead of dev-master
- Add PHPUnit as a dev dependency
- Replace require_once with require to always get the autoloader instance

### CODE REVIEW

**Comment by MacDada** [comment]
+1 waiting for it…

**Comment by marijn** [comment]
Sorry for the delay. Thanks for the ping :smile:

**Comment by MacDada** [comment]
Does it really need symfony/routing 2.1.*?

https://packagist.org/packages/silex/silex#dev-master
Silex wants a new version (>=2.3,<2.4-dev)

**Comment by marijn** [comment]
I don't think so. Not sure how that slipped in. Would you mind opening a PR for that?

**Comment by MacDada** [comment]
https://github.com/pink-tie/JMSSerializerServiceProvider/pull/11

**Pull request merged**
