### PR TITLE
Composer json fix

### PR DESCRIPTION
**Pull request by jmather**
Need to lock serializer version down in json until provider can be updated for new serializer bundle dependancies. Also will need a new tag to 0.1.1 (I think).

### CODE REVIEW

**Comment by marijn** [comment]
@jmather thanks for your PRs. Greatly appreciated. I updated the `composer.lock` file myself, usually it is best to send those in the same PR. Nevertheless thanks for your input :smile:

**Comment by marijn** [comment]
There is also a new tag available per your suggestion: `0.1.1`.

**Comment by jmather** [comment]
Oy. Forgot about the lock file. Sorry about that! I'm not sure how much the lock file actually plays in when installed through dependency though.

Thanks!

**Comment by marijn** [comment]
No worries. Thanks for your work, it's greatly appreciated!

**Pull request merged**
