### PR TITLE
Fixed readme file for changed format of how JMS Serializer installes (no...

### PR DESCRIPTION
**Pull request by jmather**
...t sure how it changed but it did)

No longer needs 'src'

### CODE REVIEW

**Comment by jmather** [comment]
Sorry, my typing is awful.

@schmittjoh seems to have changed how it installs via composer, so the update is needed (how it affects older installs, i'm stumped, but it does!)

**Comment by marijn** [comment]
Thanks for the PR. I'm currently on the road so I trust the passing build status is enough reason to merge :smile:.

I'll currently am unable to release a new version without a machine available. I'll do that on monday.

Thanks, enjoy your weekend.

**Comment by marijn** [comment]
Ok. Didn't realize this is only a documentation improvement :blush: Thanks anyway.

**Comment by jmather** [comment]
That's ok, there's more going on with it, but if you're on the road, i'll let it be over the weekend and maybe we can talk and sort it out Monday.

There's also the hope that perhaps it will mysteriously fix itself the same way it broke itself.

Have fun traveling! :)

**Comment by jmather** [comment]
N/m on the other issue -- it was another test which had the '/src' bit still and a bad cache directory value -- all sorted out now. :)

**Pull request merged**
